name: CI frontend math&magique

on:
  pull_request:
    branches: [main, dev-feature]

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Install dependencies 
        run: npm install
        working-directory: ./

      - name: Run lint 
        run: npm run lint
        working-directory: ./
     